from __future__ import annotations

from pydantic import ConfigDict
from pydantic.dataclasses import dataclass

from trapi_object_modeling.attribute import Attribute
from trapi_object_modeling.edge_binding import EdgeBinding
from trapi_object_modeling.path_binding import PathBinding
from trapi_object_modeling.shared import CURIE, AuxGraphID, QEdgeID, QPathID
from trapi_object_modeling.utils.object_base import TOMBaseObject


@dataclass(kw_only=True, config=ConfigDict(extra="allow"))
class BaseAnalysis(TOMBaseObject):
    """An analysis is a dictionary that contains information about the result tied to a particular service.

    Each Analysis is generated by a single reasoning service, and describes the
    outputs of analyses performed by the reasoner on a particular
    Result (e.g. a result score), along with provenance information
    supporting the analysis (e.g. method or data that supported
    generation of the score).
    """

    resource_id: CURIE
    """The id of the resource generating this Analysis."""

    score: float | None = None
    """A numerical score associated with this result indicating the relevance or confidence of this result relative to others in the returned set.

    Higher MUST be better.
    """

    support_graphs: list[AuxGraphID] | None = None
    """This is a list of references to Auxiliary Graph instances that supported the analysis of a Result as performed by the reasoning service.

    Each item in the list is the key of a single Auxiliary Graph.
    """

    scoring_method: str | None = None
    """An identifier and link to an explanation for the method used to generate the score."""

    attributes: list[Attribute] | None = None
    """The attributes of this particular Analysis."""


@dataclass(kw_only=True, config=ConfigDict(extra="allow"))
class Analysis(BaseAnalysis):
    """An analysis for results from a non-Pathfinder query SHOULD have edge_bindings and SHOULD NOT have path_bindings."""

    edge_bindings: dict[QEdgeID, list[EdgeBinding]]
    """The dictionary of input Query Graph to Knowledge Graph edge bindings where the dictionary keys are the key identifiers of the Query Graph edges and the associated values of those keys are instances of EdgeBinding schema type (see below).

    This value is an array of EdgeBindings since a given query edge may
    resolve to multiple Knowledge Graph Edges.
    """


@dataclass(kw_only=True, config=ConfigDict(extra="allow"))
class PathfinderAnalysis(BaseAnalysis):
    """An analysis for results from a Pathfinder query SHOULD have path_bindings and SHOULD NOT have edge_bindings."""

    path_bindings: dict[QPathID, list[PathBinding]]
    """The dictionary of input Query Graph paths to Analysis paths, specifically only for pathfinder queries."""
