from __future__ import annotations

import copy
from typing import Annotated, TypeVar

from pydantic import Field
from typing_extensions import override

from translator_tom.models.attribute import Attribute
from translator_tom.models.edge_binding import EdgeBinding
from translator_tom.models.path_binding import PathBinding
from translator_tom.models.shared import CURIE, AuxGraphID, QEdgeID, QPathID
from translator_tom.utils.object_base import TOMBase

__all__ = ["Analysis"]

_Binding = TypeVar("_Binding", EdgeBinding, PathBinding)


class Analysis(TOMBase):
    """An Analysis is a dictionary that contains information about the result tied to a particular service.

    Each Analysis is generated by a single reasoning service, and describes the
    outputs of analyses performed by the reasoner on a particular Result
    (e.g. a result score), along with provenance information supporting the
    analysis (e.g. method or data that supported generation of the score).
    """

    resource_id: CURIE
    """The infores id of the resource generating this Analysis."""

    edge_bindings: Annotated[dict[QEdgeID, EdgeBinding] | None, Field(min_length=1)] = (
        None
    )
    """The dictionary of input Query Graph to Knowledge Graph edge bindings where the dictionary keys are the key identifiers of the Query Graph edges and the associated values of those keys are instances of EdgeBinding schema type (see below).

    Because a given QEdge may have multiple knowledge Edges bound in the
    result, the EdgeBinding object may list multiple knowledge Edges.
    """

    path_bindings: Annotated[dict[QPathID, PathBinding] | None, Field(min_length=1)] = (
        None
    )
    """The dictionary of input QueryGraph paths to Analysis paths, specifically used only for pathfinder queries."""

    score: float | None = None
    """A numerical score associated with this result indicating the relevance or confidence of this result relative to others in the returned set.

    Higher MUST be better.
    """

    support_graphs: Annotated[list[AuxGraphID] | None, Field(min_length=1)] = None
    """This is a list of references to AuxiliaryGraph instances that supported the analysis of a Result as performed by the reasoning service.

    Each item in the list is the key of a single AuxiliaryGraph.
    """

    scoring_method: str | None = None
    """An identifier and link to an explanation for the method used to generate the score."""

    attributes: list[Attribute] | None = None
    """The attributes of this particular Analysis."""

    @property
    def edge_bindings_dict(self) -> dict[QEdgeID, EdgeBinding]:
        """Get the edge_bindings as a guaranteed dict, even if they are represented as None."""
        return self.edge_bindings if self.edge_bindings is not None else {}

    @property
    def path_bindings_dict(self) -> dict[QPathID, PathBinding]:
        """Get the path_bindings as a guaranteed dict, even if they are represented as None."""
        return self.path_bindings if self.path_bindings is not None else {}

    @property
    def support_graphs_list(self) -> list[AuxGraphID]:
        """Get the support graphs as a guaranteed list, even if they are represented as None."""
        return self.support_graphs if self.support_graphs is not None else []

    @property
    def attributes_list(self) -> list[Attribute]:
        """Get the attributes as a guaranteed list, even if they are represented as None."""
        return self.attributes if self.attributes is not None else []

    @override
    def _hash_repr(self) -> object:
        return (
            self.resource_id,
            self.score,
            frozenset(self.support_graphs_list),
            self.scoring_method,
            {
                qedge_id: binding.hash()
                for qedge_id, binding in self.edge_bindings_dict.items()
            },
            {
                qpath_id: binding.hash()
                for qpath_id, binding in self.path_bindings_dict.items()
            },
        )

    def update(self, other: Analysis) -> None:
        """Update the analysis in-place with another analysis."""
        if (not self.attributes) and other.attributes:
            self.attributes = other.attributes
        elif self.attributes and other.attributes:
            Attribute.merge_attribute_lists(self.attributes, other.attributes)

        if (not self.support_graphs) and other.support_graphs:
            self.support_graphs = other.support_graphs
        elif self.support_graphs and other.support_graphs:
            self.support_graphs = list(
                set(self.support_graphs) | set(other.support_graphs)
            )

        if other.edge_bindings:
            if self.edge_bindings is None:
                self.edge_bindings = copy.deepcopy(other.edge_bindings)
            else:
                self._merge_binding_map(self.edge_bindings, other.edge_bindings)

        if other.path_bindings:
            if self.path_bindings is None:
                self.path_bindings = copy.deepcopy(other.path_bindings)
            else:
                self._merge_binding_map(self.path_bindings, other.path_bindings)

    @staticmethod
    def _merge_binding_map(
        target: dict[str, _Binding], other: dict[str, _Binding]
    ) -> None:
        """Merge `other` into `target` in-place, unioning each binding's ids per key."""
        for key, binding in other.items():
            existing = target.get(key)
            if existing is None:
                target[key] = copy.deepcopy(binding)
            else:
                # ids identify a set of KG edges/aux graphs; union, deduped, order-stable.
                existing.ids = list(dict.fromkeys((*existing.ids, *binding.ids)))
