from __future__ import annotations

import copy
from typing import override

from translator_tom.models.attribute import Attribute
from translator_tom.models.edge_binding import EdgeBinding
from translator_tom.models.path_binding import PathBinding
from translator_tom.models.shared import CURIE, AuxGraphID, QEdgeID, QPathID
from translator_tom.utils.hash import tomhash
from translator_tom.utils.object_base import TOMBaseObject


class BaseAnalysis(TOMBaseObject):
    """An analysis is a dictionary that contains information about the result tied to a particular service.

    Each Analysis is generated by a single reasoning service, and describes the
    outputs of analyses performed by the reasoner on a particular
    Result (e.g. a result score), along with provenance information
    supporting the analysis (e.g. method or data that supported
    generation of the score).
    """

    resource_id: CURIE
    """The id of the resource generating this Analysis."""

    score: float | None = None
    """A numerical score associated with this result indicating the relevance or confidence of this result relative to others in the returned set.

    Higher MUST be better.
    """

    support_graphs: list[AuxGraphID] | None = None
    """This is a list of references to Auxiliary Graph instances that supported the analysis of a Result as performed by the reasoning service.

    Each item in the list is the key of a single Auxiliary Graph.
    """

    scoring_method: str | None = None
    """An identifier and link to an explanation for the method used to generate the score."""

    attributes: list[Attribute] | None = None
    """The attributes of this particular Analysis."""

    @property
    def support_graphs_list(self) -> list[AuxGraphID]:
        """Get the support graphs as a guaranteed list, even if they are represented as None."""
        return self.support_graphs if self.support_graphs is not None else []

    @property
    def attributes_list(self) -> list[Attribute]:
        """Get the attributes as a guaranteed list, even if they are represented as None."""
        return self.attributes if self.attributes is not None else []

    @override
    def hash(self) -> str:
        return tomhash(
            (
                self.resource_id,
                self.score,
                frozenset(self.support_graphs_list),
                self.scoring_method,
            )
        )

    def _update_base(self, other: BaseAnalysis) -> None:
        if (not self.attributes) and other.attributes:
            self.attributes = other.attributes
        elif self.attributes and other.attributes:
            Attribute.merge_attribute_lists(self.attributes, other.attributes)

        if (not self.support_graphs) and other.support_graphs:
            self.support_graphs = other.support_graphs
        elif self.support_graphs and other.support_graphs:
            self.support_graphs = list(
                set(self.support_graphs) | set(other.support_graphs)
            )


class Analysis(BaseAnalysis):
    """An analysis for results from a non-Pathfinder query SHOULD have edge_bindings and SHOULD NOT have path_bindings."""

    edge_bindings: dict[QEdgeID, list[EdgeBinding]]
    """The dictionary of input Query Graph to Knowledge Graph edge bindings where the dictionary keys are the key identifiers of the Query Graph edges and the associated values of those keys are instances of EdgeBinding schema type (see below).

    This value is an array of EdgeBindings since a given query edge may
    resolve to multiple Knowledge Graph Edges.
    """

    @override
    def hash(self) -> str:
        return tomhash(
            (
                super().hash(),
                {
                    qedge_id: frozenset(b.hash() for b in bindings)
                    for qedge_id, bindings in self.edge_bindings.items()
                },
            )
        )

    def update(self, other: Analysis) -> None:
        """Update the analysis in-place with another analysis."""
        self._update_base(other)
        for k in other.edge_bindings:
            if k in self.edge_bindings:
                # deepcopy to avoid modifying other
                self.edge_bindings[k] = list(
                    set(self.edge_bindings[k])
                    | set(copy.deepcopy(other.edge_bindings[k]))
                )
            else:
                self.edge_bindings[k] = copy.deepcopy(other.edge_bindings[k])


class PathfinderAnalysis(BaseAnalysis):
    """An analysis for results from a Pathfinder query SHOULD have path_bindings and SHOULD NOT have edge_bindings."""

    path_bindings: dict[QPathID, list[PathBinding]]
    """The dictionary of input Query Graph paths to Analysis paths, specifically only for pathfinder queries."""

    @override
    def hash(self) -> str:
        return tomhash(
            (
                super().hash(),
                {
                    qpath_id: frozenset(b.hash() for b in bindings)
                    for qpath_id, bindings in self.path_bindings.items()
                },
            )
        )

    def update(self, other: PathfinderAnalysis) -> None:
        """Update the analysis in-place with another analysis."""
        self._update_base(other)
        for k in other.path_bindings:
            if k in self.path_bindings:
                # deepcopy to avoid modifying other
                self.path_bindings[k] = list(
                    set(self.path_bindings[k])
                    | set(copy.deepcopy(other.path_bindings[k]))
                )
            else:
                self.path_bindings[k] = copy.deepcopy(other.path_bindings[k])
